### ISSUE TITLE
File extension not understood

### ISSUE THREAD

**Issue by PatrickvanZalm** [MannLabs/alphatims#180]
Hi all,

Im trying to pack alphatims in a docker container and run use the CLI version of the tool. Here I use Alphatims 0.3.2 but I run into an error where it does not recognize the file extension. I run the line below and get the following output. The bruker-Directory without quotations does lead to the same error.

> 
> root@70689f3fe955:/var/opt/project# alphatims export hdf "/var/opt/project/K562_post_1_S1-A1_1_12197.d/"
> *******************
> * AlphaTims 0.3.2 *
> *******************
> 2022-04-09 21:09:09> Platform information:
> 2022-04-09 21:09:09> system        - Linux
> 2022-04-09 21:09:09> release       - 5.13.0-30-generic
> 2022-04-09 21:09:09> version       - #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
> 2022-04-09 21:09:09> machine       - x86_64
> 2022-04-09 21:09:09> processor     - 
> 2022-04-09 21:09:09> cpu count     - 24
> 2022-04-09 21:09:09> cpu frequency - 1.66 Mhz
> 2022-04-09 21:09:09> ram           - 6.3/11.7 Gb (available/total)
> 2022-04-09 21:09:09> 
> 2022-04-09 21:09:09> Python information:
> 2022-04-09 21:09:09> alphatims  - 0.3.2
> 2022-04-09 21:09:09> bokeh      - 
> 2022-04-09 21:09:09> click      - 8.1.2
> 2022-04-09 21:09:09> datashader - 
> 2022-04-09 21:09:09> h5py       - 3.6.0
> 2022-04-09 21:09:09> hvplot     - 
> 2022-04-09 21:09:09> numba      - 0.55.1
> 2022-04-09 21:09:09> pandas     - 1.4.2
> 2022-04-09 21:09:09> psutil     - 5.9.0
> 2022-04-09 21:09:09> python     - 3.9.12
> 2022-04-09 21:09:09> python-lzf - 
> 2022-04-09 21:09:09> pyzstd     - 0.15.2
> 2022-04-09 21:09:09> selenium   - 
> 2022-04-09 21:09:09> tqdm       - 4.64.0
> 2022-04-09 21:09:09> 
> 2022-04-09 21:09:09> Current AlphaTims version is up-to-date with GitHub.
> 2022-04-09 21:09:09> 
> 2022-04-09 21:09:09> Running CLI command `alphatims export hdf` with parameters:
> 2022-04-09 21:09:09> bruker_raw_data     - /var/opt/project/K562_post_1_S1-A1_1_12197.d/
> 2022-04-09 21:09:09> disable_log_stream  - False
> 2022-04-09 21:09:09> disable_overwrite   - False
> 2022-04-09 21:09:09> enable_compression  - False
> 2022-04-09 21:09:09> log_file            - /usr/local/lib/python3.9/site-packages/alphatims/logs/log_20220409210909.txt
> 2022-04-09 21:09:09> threads             - 23
> 2022-04-09 21:09:09> 
> 2022-04-09 21:09:10> Importing data from /var/opt/project/K562_post_1_S1-A1_1_12197.d/
> 2022-04-09 21:09:10> Something went wrong, execution incomplete!
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/alphatims/cli.py", line 114, in parse_cli_settings
>     yield kwargs
>   File "/usr/local/lib/python3.9/site-packages/alphatims/cli.py", line 272, in export_hdf
>     data = alphatims.bruker.TimsTOF(parameters["bruker_raw_data"])
>   File "/usr/local/lib/python3.9/site-packages/alphatims/bruker.py", line 1022, in __init__
>     raise NotImplementedError(
> NotImplementedError: WARNING: file extension not understood

`

**Comment by PatrickvanZalm** [comment]
Forget what I said. resolved by using the same solution as in this post.
https://github.com/MannLabs/alphatims/issues/154

The slash at the end is the issue.
